### ISSUE TITLE
Working with Angular 1.3*

### ISSUE THREAD

**Issue by doodirock** [jirikavi/AngularJS-Toaster#78]
Is this working with 1.3?  When I add it to my project using the ng-animate 1.2.8 I get a ton of errors.  

TypeError: object is not a function

**Comment by doodirock** [comment]
This issue is an update in ngAnimate.
